/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminPortalRouteImport } from './routes/adminPortal'
import { Route as IndexRouteImport } from './routes/index'

const AdminPortalRoute = AdminPortalRouteImport.update({
  id: '/adminPortal',
  path: '/adminPortal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminPortal': typeof AdminPortalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminPortal': typeof AdminPortalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adminPortal': typeof AdminPortalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adminPortal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adminPortal'
  id: '__root__' | '/' | '/adminPortal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminPortalRoute: typeof AdminPortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/adminPortal': {
      id: '/adminPortal'
      path: '/adminPortal'
      fullPath: '/adminPortal'
      preLoaderRoute: typeof AdminPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminPortalRoute: AdminPortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
