// Mock data matching server Prisma MedicalLog model
export const mockMedicalLogs = [
  {
    id: 'ml-001',
    logged_at: '2024-05-01T10:30:00Z',
    category: 'MEDICAL',
    general_notes: 'Annual vaccination — rabies booster administered.',
    behavior_notes: null,
    qty_administered: 1.0,
    dose: '1 mL',
    administered_at: '2024-05-01T10:15:00Z',
    prescription: null,
    documents: null,
    foster_user_id: null,
    animal_id: '1',
    animal_name: 'Chewy',
    assignment_id: null,
    medication_id: null,
  },
  {
    id: 'ml-002',
    logged_at: '2024-05-03T14:00:00Z',
    category: 'BEHAVIORAL',
    general_notes: null,
    behavior_notes: 'Showing signs of anxiety during feeding. Recommend enrichment toys.',
    qty_administered: null,
    dose: null,
    administered_at: null,
    prescription: null,
    documents: null,
    foster_user_id: 'foster-user-1',
    animal_id: '2',
    animal_name: 'Bailey',
    assignment_id: null,
    medication_id: null,
  },
  {
    id: 'ml-003',
    logged_at: '2024-05-05T09:00:00Z',
    category: 'VETERINARY',
    general_notes: 'Spay surgery completed without complications. Recovery expected in 10 days.',
    behavior_notes: null,
    qty_administered: null,
    dose: null,
    administered_at: null,
    prescription: 'Carprofen 25mg twice daily for 5 days',
    documents: null,
    foster_user_id: null,
    animal_id: '3',
    animal_name: 'Luna',
    assignment_id: null,
    medication_id: null,
  },
  {
    id: 'ml-004',
    logged_at: '2024-05-07T11:45:00Z',
    category: 'MEDICAL',
    general_notes: 'Flea treatment applied. No adverse reactions observed.',
    behavior_notes: null,
    qty_administered: 1.0,
    dose: '0.5 mL topical',
    administered_at: '2024-05-07T11:30:00Z',
    prescription: null,
    documents: null,
    foster_user_id: 'foster-user-1',
    animal_id: '7',
    animal_name: 'Shadow',
    assignment_id: null,
    medication_id: null,
  },
  {
    id: 'ml-005',
    logged_at: '2024-05-10T08:20:00Z',
    category: 'BEHAVIORAL',
    general_notes: null,
    behavior_notes: 'Aggressive toward other dogs during group play. Recommend solo exercise time.',
    qty_administered: null,
    dose: null,
    administered_at: null,
    prescription: null,
    documents: null,
    foster_user_id: null,
    animal_id: '8',
    animal_name: 'Buddy',
    assignment_id: null,
    medication_id: null,
  },
  {
    id: 'ml-006',
    logged_at: '2024-05-12T15:30:00Z',
    category: 'VETERINARY',
    general_notes: 'Dental cleaning performed. Two teeth extracted due to decay.',
    behavior_notes: null,
    qty_administered: null,
    dose: null,
    administered_at: null,
    prescription: 'Amoxicillin 50mg twice daily for 7 days',
    documents: null,
    foster_user_id: null,
    animal_id: '5',
    animal_name: 'Whiskers',
    assignment_id: null,
    medication_id: null,
  },
  {
    id: 'ml-007',
    logged_at: '2024-05-14T13:00:00Z',
    category: 'MEDICAL',
    general_notes: 'Deworming treatment administered. Follow-up in two weeks.',
    behavior_notes: null,
    qty_administered: 2.0,
    dose: '2 tablets',
    administered_at: '2024-05-14T12:45:00Z',
    prescription: null,
    documents: null,
    foster_user_id: 'foster-user-2',
    animal_id: '2',
    animal_name: 'Bailey',
    assignment_id: null,
    medication_id: null,
  },
  {
    id: 'ml-008',
    logged_at: '2024-05-16T10:00:00Z',
    category: 'BEHAVIORAL',
    general_notes: null,
    behavior_notes: 'Improved socialization with other cats. Responding well to clicker training.',
    qty_administered: null,
    dose: null,
    administered_at: null,
    prescription: null,
    documents: null,
    foster_user_id: 'foster-user-1',
    animal_id: '10',
    animal_name: 'Milo',
    assignment_id: null,
    medication_id: null,
  },
];
